### ISSUE TITLE
Render error with AE fluid pattern

### ISSUE THREAD

**Issue by Shepherd23333** [MorphismMC/Epimorphism-Core#3]
Crashed when shift to clear the pattern.
ae2-uel-extended-v0.55.24-0.3.4-rv6-stable-7, Fluid Craft for AE2-2.4.33-r, EPCore 0.02alpha
cr:https://mclo.gs/OPKTMCA

**Comment by gate-guardian** [comment]
The crash report shows that the problem seems to be due to the Encoded Pattern of AE2 Fluid Crafting Rework mistakenly using the renderer I attached for the Data Item (now Data Stick will render the product when Shift is pressed), but the development work for EPCore on 1.12 has stopped and the project will be migrated to 1.20 to support GTM. Sorry!
